### ISSUE TITLE
Checkout to `master` is failing

### ISSUE THREAD

**Issue by arturomf94** [boa-dev/criterion-compare-action#25]
I have a workflow as follows:

```
name: Rust benchmarks

on: [pull_request]
jobs:
  runBenchmark:
    name: run benchmark
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: jasonwilliams/criterion-compare-action@move_to_actions
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

```

It's failing with:

```
error: pathspec 'master' did not match any file(s) known to git
```

Am I missing anything here or could it be a bug?
